pingidentity/helm-charts

charts/ping-devops/Chart.yaml
charts/ping-devops/values.yaml
docs/config/image.md
docs/config/probes.md

* Changing default pullPolicy to Always.  Helps when using changing edge tag
* Increasing liveness/readiness probe timeoutSeconds to 5 as 1 is often to short

Changine default pullPolicy and probe timeouts

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/global/configmap.yaml
charts/ping-devops/templates/pinglib/_deployment.yaml
charts/ping-devops/templates/pinglib/_helpers.tpl
charts/ping-devops/templates/pinglib/_merge-util.yaml
charts/ping-devops/templates/pinglib/_statefulset.yaml
charts/ping-devops/templates/pinglib/_yamlSnippets.tpl
docs/examples/everything.md
docs/examples/everything.yaml
docs/getting-started.md

This change will create a configmap `{release-name}-global-env-vars` which will be pulled in optionally by all deployments/statefulsets, if that product is enabled.  As an example, it will create the following:
```
apiVersion: v1
kind: ConfigMap
data:
PA_ENGINE_PRIVATE_HOSTNAME: demo-pingaccess
PD_ENGINE_PRIVATE_HOSTNAME: demo-pingdirectory
PDG_ENGINE_PRIVATE_HOSTNAME: demo-pingdatagovernance
PDS_ENGINE_PRIVATE_HOSTNAME: demo-pingdatasync
PF_ADMIN_PRIVATE_HOSTNAME: demo-pingfederate-admin
PF_ENGINE_PRIVATE_HOSTNAME: demo-pingfederate-engine
```
This will be key in supporting our server-profiles, so that integration will operate correctly between products.
> For Example: pingfederate will be able to properly talk to the pingdirectory instance using the correct service name.
> Note: We may …

v0.2.9 - provide proper service names to PRIVATE_HOSTNAMES in global-env-vars configmap

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pingdirectory/service-cluster.yaml
docs/release-notes.md

* [Issue #83](https://github.com/pingidentity/helm-charts/issues/83) - Remove old pingdirectory tag check when creating service-cluster.  This caused issues when creating a pingdirectory deployment with most recent tags (tags other than edge or 2012).

Release 0.4.3

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pinglib/_workload.tpl
charts/ping-devops/values.yaml
docs/config/volume-mounts.md
docs/config/workload.md
docs/examples/everything.yaml
docs/release-notes.md
mkdocs.yml

From Release Notes:
* [Issue #80](https://github.com/pingidentity/helm-charts/issues/80) - Add support for importing a secret containing license into the container.
Adds ability to add secret and configMap data to a container via a VolumeMount.  A good use of this practice - bringing product
licenses into the container.
!!! note "Example of creating 3 volume mounts in container from secret and configMap"
```yaml
pingfederate-admin
secretVolumes:
pingfederate-license:
items:
license: /opt/in/instance/server/default/conf/pingfederate.lic
hello: /opt/in/instance/server/default/hello.txt
configMapVolumes:
pingfederate-props:
items:
pf-props: /opt/in/etc/pingfederate.properties
```
In this case, a secret (called pingfederate-license) and configMap (called pingfederate-props) will bring in a …

Release 0.4.4

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/NOTES.txt
charts/ping-devops/values.yaml
docs/release-notes.md

* [Issue #89](https://github.com/pingidentity/helm-charts/issues/89) - Update default workload resource cpu/memory request sizes.
Updating defaults to create a usage better reflecting actual memory usage by product. And minimizing amount of CPU needed
as testing generally utilizes very little.  Of course, it is definitely recommended that production deployments specify amount of
cpu and memory required and limited to.
Current defaults are set to:
```
#-------------------------------------------------------------------------------------
#
#-------------------------------------------------------------------------------------
#
#
#
#-------------------------------------------------------------------------------------
```

Issue #89 - Adding new defaults for cpu and memory

---

charts/ping-devops/Chart.yaml
charts/ping-devops/values.yaml
docs/release-notes.md

* [Issue #100](https://github.com/pingidentity/helm-charts/issues/100) - Change pingfederate-engine HPA to a default of disabled
Changing the default value `pingfederate-engine.clustering.autoscaling.enabled=false`, since the default
CPU Request is set to 0.

Release 0.4.8

---

charts/ping-devops/Chart.yaml
charts/ping-devops/values.yaml
docs/examples/everything.yaml
docs/examples/pingfederate.yaml
docs/examples/simple-sync.yaml
docs/release-notes.md

-   Update the default global image tag in base values.yaml and remove edge from example yamls.

Release 0.4.9 - Update default global image tag to 2102 (Feb 2021)

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/NOTES.txt
charts/ping-devops/templates/pinglib/_yamlSnippets.tpl
charts/ping-devops/values.yaml
docs/config/private-cert.md
docs/release-notes.md

* [Issue #103](https://github.com/pingidentity/helm-charts/issues/103) - Provide ability to add additional alt-names/alt-ips to private cert generation
Allow for a privateCert structure to contain optional arrays `additionalHosts` and `additionalIPs`:
```
pingaccess-admin:
privateCert:
generate: true
additionalHosts:
- pingaccess-admin.west-cluster.example.com
- pa-admin.west-cluster.example.com
additionalIPs:
- 123.45.67.8
```
In addition, if the ingress for the product is enabled, the host(s) created for that ingress will also be added to the alt-names.
The above example (with an ingress) will create a cert used by pingaccess-admin containing:
```
Certificate:
Data:
...
Signature Algorithm: sha256WithRSAEncryption
Issuer: CN=pingaccess-admin
...
X509v3 extensions:
...
X509v3 Subject …
```

Release 0.5.0

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/global/configmap.yaml
charts/ping-devops/templates/pinglib/_configmap.tpl
charts/ping-devops/values.yaml
docs/config/private-cert.md
docs/config/vault.md
docs/config/workload.md
docs/release-notes.md

* [Issue #121](https://github.com/pingidentity/helm-charts/issues/121) - Create global-env-vars hosts/ports
for all products regardless if enabled
The status of this config map is used to form the checksum for the products. This will ensure that a simple
addition/deletion of a product from the deployed mix won't cause all products to be restarted.
* [Issue #122](https://github.com/pingidentity/helm-charts/issues/122) - Update image.tag to 2103 (March 2021)
The image tag is modified to 2103. This includes:
* Security Context on StatefulSets to include a fsGroup=9999 (same as gid)
* Update the services ContainerPort to unprivileged ports (i..e. 636 --> 1636)

Release 0.5.3

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pinglib/_workload.tpl
docs/release-notes.md

* [Issue #126](https://github.com/pingidentity/helm-charts/issues/126) - Unable to mount secretVolume and configMapVolumes simultaneously
Due to the fact that volumes: is an array of items volumes: usage with secret or configMap volumes exosed
the issue that multiple volumes: entries were used, and only kept the last one.  Fix included only using
volumes: once.  Note that the template will end up with a `volumes: null` if none are
set (i.e. deployment with no Secret/ConfigMap volumes), but that is ok.

Release 0.5.4

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pinglib/_workload.tpl
docs/release-notes.md

* [Issue #126](https://github.com/pingidentity/helm-charts/issues/126) - Unable to mount secretVolume and configMapVolumes simultaneously
This is one additional fix to the the same thing fixed in 0.5.4.  `volumeMounts:` had the same issue as `volumes:`.  This
completes and resolves issue #126.

Release 0.5.5

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/NOTES.txt
charts/ping-devops/templates/global/secret-cert.yaml
charts/ping-devops/templates/pingdirectoryproxy/configmap.yaml
charts/ping-devops/templates/pingdirectoryproxy/service-cluster.yaml
charts/ping-devops/templates/pingdirectoryproxy/service.yaml
charts/ping-devops/templates/pingdirectoryproxy/workload.yaml
charts/ping-devops/values.yaml
docs/examples/everything.yaml
docs/release-notes.md

* Closes #133 - Change default pingdirectory values
(container.resources.requests.cpu=50m and container.replicaCount=1)
Setting the cpu request to 50m, will provide at last some reservation of CPU, so that if there are multiple nodes,
it will better even out the load.
Additionally, setting the replicaCount to 1 by default, as many cases in development, there isn't a great need to
have multiple replicas. If this is the case, simply set pingdirectory.container.replicaCount=2 or any number of replica's.
* Closes #132  - Adding PingDirectoryProxy to mix of products

Release 0.5.6

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pinglib/_service-cluster.tpl
charts/ping-devops/values.yaml
docs/release-notes.md

* [Issue #136](https://github.com/pingidentity/helm-charts/issues/136) ClusterIP Services
port/targetPort be set to the containerPort
Since the ClusterIP Services (aka Headless services) only provide access to the underlying container
IP and port.  The port, and by default targetPort, will be set to the containerPort value.  The helm
charts will start requiring the containerPort for any service where clusterService:true is set, otherwise
it will fail with an error message.
* [Issue #138](https://github.com/pingidentity/helm-charts/issues/138) Update image.tag to 2104 (April 2021)

Release 0.5.7

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pingfederate-engine/configmap.yaml
docs/release-notes.md

* [Issue #141](https://github.com/pingidentity/helm-charts/issues/141) Fix DNS_QUERY_LOCATION on pingfederate-engine configmap.yaml
Resolves an issue with the DNS_QUERY_LOCATION when pingfederate clustering is used for >1 pingfederate-engines

Release 0.5.8

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pinglib/_workload.tpl
docs/release-notes.md

* [Issue #148](https://github.com/pingidentity/helm-charts/issues/148) Calculate checksum of ConfigMaps based
on the data rather than entire ConfigMap file
This will only use the ConfigMap.data when creating checksums in workload rather than using the
entire file.  It will result in no checksum change when labels/annotations are the only thing changing.
A good example is the helm chart version, which changes the label, but not data.

Release 0.6.1

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pinglib/_vaultSecrets.tpl
charts/ping-devops/templates/pinglib/_workload.tpl
charts/ping-devops/values.yaml
docs/release-notes.md

* [Issue #151](https://github.com/pingidentity/helm-charts/issues/151) Add support for Container LifeCycle Event Hooks
Adding following to values.yaml
```yaml
global:
############################################################
#
############################################################
lifecyle: {}
```
* General cleanup of values.yaml comments
* Setting default `externalImages.pingtoolkit` tag to 2104, and removing `edge` tag from `ldap-sdk-tools` image
which will now default to same `global.image.tag` setting (currently 2104)

Release 0.6.2

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/NOTES.txt
charts/ping-devops/templates/pinglib/_workload.tpl
charts/ping-devops/values.yaml
docs/release-notes.md

* [Issue #158](https://github.com/pingidentity/helm-charts/issues/158) Increment default tag to 2105
Sidecars and initContainers are valuable for a multitude of reasons - log forwarding, metric exporting, backup jobs. Because of this they can also have many ways of being configured.
Allow for defining three top level maps to provide details for:
* sidecars - Defines sidecar containers to be run alongside product containers.
* initContainers - Defines initContainers to be run before product containers.
* volumes - Defines volumes used by sidecars, initContainers and product containers.
```
sidecars:
pd-access-logger:
name: pd-access-log-container
image: pingidentity/pingtoolkit:2105
volumeMounts:
- mountPath: /tmp/pd-access-logs/
name: pd-access-logs
readOnly: false
statsd-exporter:
name: …
```

Release 0.6.4

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/NOTES.txt
charts/ping-devops/templates/global/configmap.yaml
charts/ping-devops/templates/global/secret-cert.yaml
charts/ping-devops/templates/pingauthorize/configmap.yaml
charts/ping-devops/templates/pingauthorize/ingress.yaml
charts/ping-devops/templates/pingauthorize/service-cluster.yaml
charts/ping-devops/templates/pingauthorize/service.yaml
charts/ping-devops/templates/pingauthorize/workload.yaml
charts/ping-devops/templates/pingauthorizepap/configmap.yaml
charts/ping-devops/templates/pingauthorizepap/ingress.yaml
charts/ping-devops/templates/pingauthorizepap/service.yaml
charts/ping-devops/templates/pingauthorizepap/workload.yaml
charts/ping-devops/values.yaml
docs/release-notes.md

Add PingAuthorize and PingAuthorizePAP to helm charts.
This includes the necessary config for PingAuthorize and PingAuthorizePAP even though
there isn't a release for 2105.  The current edge release is required to use the default
server-profiles provided in the values.yaml.  Once the global tag is changed to 2106 (over next
few days) PingAuthorize will be default for use over PingDataGoverance.  This will be tracked in
a ticket released 2105.
pingdataconsole:
enabled: true
pingdirectory:
enabled: true
pingauthorize:
image:
tag: 8.3.0.0-edge
enabled: true
pingauthorizepap:
enabled: true

Release 0.6.5 - Addig PingAuthorize/PAP

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pinglib/_test_postman.tpl
charts/ping-devops/templates/tests/testFramework.yaml
charts/ping-devops/values.yaml
docs/release-notes.md

* [Issue #160](https://github.com/pingidentity/helm-charts/issues/160) Change default image tag to 2106
* [Issue #166](https://github.com/pingidentity/helm-charts/issues/166) Add securityContexts to testFramework containers
* Adding ability to provide a securityContext at the following levels:
* Changing the default finalStep image to busybox
```yaml
testFramework:
...
#########################################################
#########################################################
securityContext:
runAsUser: 1000
runAsGroup: 2000
...
testSteps:
- name: 01-init-example
...
securityContext:
runAsUser: ...
...
finalStep:
securityContext:
runAsUser: ...
```
* [Issue #167](https://github.com/pingidentity/helm-charts/issues/167) Disable testFramework by default
To enable, simply:
```yaml …
```

Release 0.6.6

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pinglib/_ingress.tpl
docs/release-notes.md

* [Issue #175](https://github.com/pingidentity/helm-charts/issues/175) Invalid ingress resources on Kubernetes clusters > 1.18
During resoluton of issue #170 providing support for ingress apiVersion v1,
the necessary ingress yaml fields wearn't updated to relfect that new version.
This is a fix.  The backend definition of the Ingress will now reflect the proper
definition based on a v1 or v1beta1 apiVersion.
Example: If KubeVersion > 1.18"
```
service:
name: https
port:
number: 443
```
Example: If KubeVersion <= 1.18"
```
serviceName: https
servicePort: 443
```

Release 0.6.8

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pingfederate-admin/configmap.yaml
charts/ping-devops/templates/pingfederate-engine/configmap.yaml
charts/ping-devops/templates/pinglib/_configmap.tpl
docs/release-notes.md

* [Issue #187](https://github.com/pingidentity/helm-charts/issues/187) Create the PUBLIC hostname/ports in the global env vars configmap all the time
Currently, the PUBLIC hostname/ports in the global env vars configmap are created if and only if the ingress in enabled.
Normally, this would be fine, except that some of the products (i.e PingFederate) use the PUBLIC environment variable to setup items like BASE URLs and redirects for the browser.  This is required for use cases when there is no ingress, but the user creates a port forward, as well as testing with no ingresses.
So, if no ingress is created, then the PUBLIC_HOSTNAMES should be set to `localhost` and the PUBLIC_PORT_* should be set to the same port as the contianerPort.
If ingress is used, then the functionality will not be …

Release 0.7.1

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pinglib/_configmap.tpl
docs/release-notes.md

* [Issue #191](https://github.com/pingidentity/helm-charts/issues/191) Change variable PF_ADMIN_BASEURL to PF_ADMIN_PUBLIC_BASEURL
Release 0.7.2 created the new variable `PF_ADMIN_BASEURL`.  Due to the current user of the same variable with added `_PUBLIC_`,  the actual variable name needs to be `PF_ADMIN_PUBLIC_BASEURL`.

Release 0.7.2

---

charts/ping-devops/Chart.yaml
charts/ping-devops/templates/pinglib/_tests.tpl
charts/ping-devops/values.yaml
docs/release-notes.md

* [Issue #194](https://github.com/pingidentity/helm-charts/issues/194) Change default envs for pingauthorize/pingauthorizepap
The current envs for pingauthroize in the values.yaml file are:
```
envs:
SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
SERVER_PROFILE_PATH: paz-pap-integration/pingauthorize
SERVER_PROFILE_PARENT: PAZ
SERVER_PROFILE_PAZ_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
SERVER_PROFILE_PAZ_PATH: baseline/pingauthorize
```
Just a side note here, the `baseline/pingauthorize` PATH includes a connection to pingdirectory, which will cause this to fail (pingauthorize https will return a 503).
If someone wants to override these, they need to be sure to uset/override the `SERVER_PROFILE_PARENT` variable, so the …

Release 0.7.3

---

charts/ping-devops/Chart.yaml
charts/ping-devops/values.yaml
docs/examples/everything.yaml
docs/release-notes.md

* [Issue #206](https://github.com/pingidentity/helm-charts/issues/206) Bump default image tag to 2108

Release 0.7.5
